apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: ejercicio
  labels:
    app: backend
    created-by: backend-team
spec:
  containers:
  - name: main
    # Se pone la imagen correcta. Se quita :v1 
    image: lemoncodersbc/go-hello-world
    ports:
      - containerPort: 80
