apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvpg
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: storagepostgres
  hostPath:
    path: /data/pvpg
