apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcpg
  namespace: ejercicio2
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: storagepostgres