apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: ejercicio2
spec:
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: demcorp/lc-todo-frontend-monolith
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: cm-todo-app
