version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      #dockerfile: Dockerfile
    environment:
      API_URI: http://topics-api:5000/api/topics
    ports:
      - 8080:3000
    networks:
      - lemoncode-challenge
    depends_on:
      - topics-api

  topics-api:
    build:
      context: ./backend
      #dockerfile: Dockerfile
    networks:
      - lemoncode-challenge
    depends_on:
      - some-mongo
    
  some-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
     - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - lemoncode-challenge

volumes:
  mongo-data:
networks:
  lemoncode-challenge: